PUT http://localhost:3001/api/users/testuser/password-change
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NDhkN2Y5Yjg5ZWVhNmZhNWRmODI1ODUiLCJpYXQiOjE2ODkyOTk3NDR9.VwSX2DZLaFE8-EsEhgE0o8-_BlLiJ4okMEkutqjWT-U

{
	"currentPassword": "secret", 
	"newPassword": "sekret"
}