DELETE http://localhost:3001/api/users/sadkaposd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhZGthcG9zZCIsImlkIjoiNjRhZjRhMGY5MDhkODk1NjQ3MjA4Mjc5IiwiaWF0IjoxNjg5MzkzMzAxfQ.JafNsCfvZe5SrC8GjjNEshWNxnWeLVqoUzAGx4XhUxY

